### PR TITLE
3pos switch

### PR DESCRIPTION
**Pull request by catx23**
this PR adds debouncing for the direction switch as well adds a delay between direction switching (except switching to stop). I also interpreted 2 HIGHs for the 'shredButton' & 'reverseButton' as invalid input. 

you can ignore the last PR and take this here instead.

### CODE REVIEW

**Comment by alromh87** [comment]
Hi,

Do you think you could avoid reformatting the code, because then it is difficult to read the changes, also I avoid delays as much as possible to keep the system as responsive as possible, so maybe theres another way to wait before changing directions.

I did dome changes thinking you will start on the weekend, sorry if i got your message wrongly, now there are some conflicts and maybe its easier to rebase your changes on the new code.

**Comment by catx23** [comment]
formatting : as you like but just to let you know - the Arduino IDE messes a lot around. There is btw. also an awesome plugin for VSCode called 'platform.io', makes Arduino coding a charm. Anyways, I will remove the formatting.

The direction delay is kinda optional and for users who use contactors (and not VFDs) and we added this because of reported short circuits and there has to be a delay definitely and it's really just for abrupt direction changes. From what I have seen it should be around 600ms - but hey as you like. We added this because of tests on real hardware :-) If you don't like it, I remove it but it's gonna bite you or others back on day.

Conflicts : no worry - you keep going I make another PR anyways. the only last thing left is the mentioned 'auto-stop-idle'. I have got around the theory and the basic code is there in another branch but this needs to be tested as well on real hardware. It basically calculates the variance of the at least last Amp 10 samples - if it's below 0.2 = it's idle, and if it's longer than 2 minutes, it stops.
g

**Comment by catx23** [comment]
for simulating blocking 'delays', I have also 2 or 3 other ways but those are ASM based and rather complicated to maintain.

**Comment by catx23** [comment]
yeah, I just checked, to simulated 'delay', I could introduce some timers/durations doing basically the same thing ... - as you like. but hey, I agree - I don't like those delays either but this seems legit.

**Pull request closed without merging**
